#!/usr/bin/python
import boto3
import json
import sys
import pprint
import collections
print('Python %s on %s' % (sys.version, sys.platform))
print ('Boto Version',boto3.__version__)

def Create_Data(item):
    Type = (item['InstanceType'])
    Placement = (item['Placement'])  # placement is a dict
    Plat = (item.get('Platform', 'Linux'))
    Az = (Placement['AvailabilityZone'])
    return (Type, Az, Plat)


client_US = boto3.client('ec2', region_name='us-east-1')
client_EU = boto3.client('ec2', region_name='eu-west-1')



Regions = [client_EU,client_US,]
regionData = []
for r in Regions:
    instances = r.describe_instances(Filters=[{'Name':'instance-type' , 'Values': ['t2.nano','t2.micro','t2.small','t2.medium','t2.large','t2.xlarge','t2.2xlarge','m4.large','m4.xlarge','m4.2xlarge','m4.4xlarge','m4.10xlarge','m4.16xlarge','m3.medium','m3.large','m3.xlarge','m3.2xlarge',
    'c4.large','c4.xlarge','c4.2xlarge','c4.4xlarge','c4.8xlarge','c3.large','c3.xlarge','c3.2xlarge','c3.4xlarge','c3.8xlarge','x1.32xlarge','x1.16xlarge','r4.large','r4.xlarge','r4.2xlarge','r4.4xlarge','r4.8xlarge','r4.16xlarge','r3.large','r3.xlarge','r3.2xlarge','r3.4xlarge','r3.8xlarge',
    'p2.xlarge','p2.8xlarge','p2.16xlarge','g2.2xlarge','g2.8xlarge','f1.2xlarge','f1.16xlarge','i3.large','i3.xlarge','i3.2xlarge','i3.4xlarge','i3.8xlarge','i3.16xlarge','d2.xlarge','d2.2xlarge','d2.4xlarge','d2.8xlarge']} ])
    regionData.append(instances)

regionReservations = [z['Reservations'] for z in regionData]

print ("Number of region rev ", len(regionReservations)) #response is a list



InstanceTypeAz = []
for rr in regionReservations:
    for res in rr:
        InstanceTypeAz.extend([Create_Data(inst) for inst in res['Instances']])



pprint.pprint(collections.Counter(InstanceTypeAz))



